### ISSUE TITLE
Feature Request: get a dialog/message box/info on dragging a new script onto a Slot to keep the current configuration

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#174]
I know I can do this with holding down ctrl, but I you don't know this..you'll never do it.

**Comment by PablosScripts** [comment]
I agree.

**Comment by prototypeGtuner** [comment]
Ctrl is used for many things by the Oses and i think it would be annoying to have to close a dialog box each time i want to update a slot. But you are right most of the users will not think about that. Maybe an easy way to do that is to have a checkbox or an area to highlight in the slot's area to keep the IC settings. When the checkbox is checked the current configuration will be automatically keep.

**Comment by J2Kbr** [comment]
I was reluctant on implement the dialog box because keep the current configuration must be a deliberated action, as this only works for the same script and same configuration descriptor. Holding CTRL while updating a memory slot means the user have full knowledge of what he/she is doing.

But I agree we were needing a solution to not lose a configuration when forgetting hold CTRL. So, with the implementation of copy/paste configurations in string format and even be able to update from script, I believe this issue can be closed #205. Please comment if you guys don't agree.
