### ISSUE TITLE
Bug: Printf Crashing Gtuner

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#231]
Gtuner crashes when printf is called too frequently in a script. (I.E. printf in main loop.)

**Comment by J2Kbr** [comment]
Gtuner IV 1.00B-62 implements measurements to prevent Gtuner from hanging due overflow of printf().

**Comment by Scachi** [comment]
Is it possible to add a warning message to the Output pane "GPC warning: Output truncated" or something like that when the output is truncated in order to prevent GTuner from hanging ?

Currently it is silently cut off and I wondered why my for loop isn't working until I recognized after some time that it is only the printf message stopping to appear and the loop is working as it should.

**Comment by PoshLemur** [comment]
Really glad to see this is being fixed! I agree with Scachi silent suppression without notification to the user is going to confuse a lot of people. 

I feel the header I made SafePrint (https://www.consoletuner.com/greslib/?w358) handled this nicely. 
When too many printfs are made, suppress and count them. Then after X seconds, print something like.
"Warning: Suppressed X calls to printf() since the previous printf(). To avoid seeing this message, don't use  printf in loops."
