### ISSUE TITLE
Feature Request: Power off wireless controllers from Gtuner IV

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#268]
If i want to turn off the controller from the controller i have to use a script. No problem with that i can put it in all my scripts. But it is not possible to do that from Gtuner IV. It would be nice to be able to turn off the wireless connected controllers one by one. Something from the Device Monitor or in the Device Configuration to choose which controller to disconnect by a single click like in Gtuner Pro.

**Comment by J2Kbr** [comment]
This is already possible, right click as indicated in the following image:
![turnoff](https://user-images.githubusercontent.com/21229433/48424309-88e2e480-e749-11e8-9e7e-b264bee915a7.png)

**Comment by prototypeGtuner** [comment]
Awesome, i'ver never see that :)
Thank you.

**Comment by seededplyr** [comment]
this is a great feature and its awesome that we have it, to improve upon it i hope you will consider to make it a small fixed button in the same row because having it in a right click menu is slightly hidden and not many people will think to right click in these parts unless they knew what they were looking for.
