### ISSUE TITLE
Display Brownout message only if genuine

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#316]
See thread here: 

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=12742&start=10

**Comment by J2Kbr** [comment]
After few tests and trying some possible options (on Gtuner and FW), no satisfactory solution was found. The reset reason "Brown-out 1V8" or "Brown-out 3V3" are actually genuine, including when plugging/unplugging an external power supply with the device already powered by PROG or OUTPUT ports. These reset reasons means: the device entered in reset state because the voltage in the 1V8 rail or in the 3V3 rail dropped below the expected value. This is a safety feature to preserve the flash memory of the micro-controller. The only thing that can be done is prevent the message to be show at all. But then -I believe- we will miss an important information when debugging issues reported by the users.
