### ISSUE TITLE
Suggestions for the input translator

### ISSUE THREAD

**Issue by NeoTechni** [J2Kbr/GtunerIV#352]
-Allow conflicts. I wanted to map both A and B on the MS Accessibility controller to R2 for acceleration but I just got errors. I assume this is cause I mapped 2 buttons to the same one, and didn't disable the one it was pointing to cause they went away when I switched it so only B mapped to R2

-Let us switch to PlayStation/Microsoft/Nintendo/etc button layouts like you can in the device monitor

**Comment by J2Kbr** [comment]
By design is not possible have two controller buttons activating the same input. The reason behind this approach was chosen was optimization for speed and size. However, you can implement this functionality with a GPC Script, example:

```
#include <xb1.gph>

main {
    if(get_actual(XB1_A) || get_actual(XB1_B)) {
        set_val(XB1_A, 0.0);
        set_val(XB1_B, 0.0);
        set_val(XB1_RT, 100.0);
    }
}
```

As for your second request, we have in this GitHub: https://github.com/J2Kbr/GtunerIV/issues/253 Will be implemented soon. ;)

Thanks.
