### ISSUE TITLE
Provide option to expand text area when uploading scripts

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#36]
Below is an example from another app. This is a common feature in most apps: 

https://i.imgur.com/ZmXo96z.jpg

**Comment by J2Kbr** [comment]
I've checked if the text input control form Qt offers this feature and, unfortunately, it doesn't. Stretching this field according to the window size is not an option because the publishing wizard works as stack of components, expecting a fixed (maximum) height from each, forcing otherwise hides other components from the page and also have undesired effect on the page scrolling.

Alternative: use shortdesc tag in a commented section on the code for the script description text.
