### ISSUE TITLE
Gtuner update not loading

### ISSUE THREAD

**Issue by Hyphen-x** [J2Kbr/GtunerIV#412]
I have had my T2 for 3years and I love it still I think it is working better every time I use it. The latest down load will not load onto the T2
PS4 T2 blue tooth module gtuner on windows 10 computer lap top.
Error message occurs just after trying to download
"Titan two programming Software has stopped working
A problem caused the program to stop working correctly.
Windows will close the program and notify you if a
solution is available"
![image](https://user-images.githubusercontent.com/45961754/113476304-93dc6380-942f-11eb-81bd-72e19bf39873.png)

**Comment by J2Kbr** [comment]
The downloaded zip file must be first extracted in order to run Gtuner IV.

Please try the following:

1. Download Gtuner IV from this link and save to your Desktop (https://www.consoletuner.com/titan-two-downloads/).
2. Unzip the file to your Desktop (right click on Gtuner.zip -> Extract All…).
3. Open the Gtuner folder and double click gtuner.exe.

Thank you.
