### ISSUE TITLE
Icon to indicate that the version of a script you have is out of date

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#96]
I figure you can use an iPhone style icon to indicate that your script is say v1.2 when the latest version is v1.3 for example. See the following mockup: 

https://i.imgur.com/GCmXNDE.jpg

To further extend this idea, maybe you could have new <changelog> meta tags that allows you to display change notes when you hover over this icon.

**Comment by J2Kbr** [comment]
My intention while doing #135 (software and firmware automatic check for newer versions) was also use the same "infrastructure" for gamepacks and scripts stored in the Titan Two memory slots.

However, this turned out to be much more challenging than I was initially thinking. The meta info stored in the memory slot are not enough to determine with reasonable precision the origin of the _bytecode_. For instance, if it came from an published work, or from the users computer. 

To implement your suggestion it would be necessary to also store in the memory slot the unique hash number of associated with the published work. Unfortunately this was not anticipated by me and there is no available space for that on the memory slots 1 to 3 (internal memory slots).

I am closing this GitHub for now, but will keep your idea in mind. Perhaps in the future I find a way to implement it. Thanks.

**Comment by Scachi** [comment]
> To implement your suggestion it would be necessary to also store in the memory slot the unique hash number of associated with the published work. Unfortunately this was not anticipated by me and there is no available space for that on the memory slots 1 to 3 (internal memory slots).

I think there is no need to store the hash directly to the T2 slots.
Why not saving that unique hash to a file in the local cache of gtuner like it is done for the .gcd files ?
As you are able to open the correct .gcd file/Interactive Configuration for the slot via the gear like icon there seems to be enough information to use it correctly then.
I think this is only relevant for stuff downloaded from the Online Resource so add some hash in the Online Resource data that gets available to GTuner during the download and creates the required file in the cache folder. Then you are able to check the link for a newer version of the script in all T2 slots.

To have an update notification for the slots without having the T2 connected (for user that don't have the prog connection always established) you could save/cache the T2 information of the slots when the T2 was connected the last time.
